[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "gator"
description = "gator project"
version = "0.0.1"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "torch==2.5.1",
    "torchvision==0.20.1",
    "lightning>=2.5.0",
    "setuptools",
    "torchmetrics",
    "scikit-learn",
    "tqdm",
    "quaternion",
    "opencv-python",
    "tyro",
    "wandb==0.25.0",
    "tensorboard>=2.20.0",
    "seaborn>=0.13.2",
    "webdataset>=1.0.2",
    "einops",
    "h5py",
    "ipywidgets",
    "ipykernel",
    "matplotlib",
    "numpy-quaternion",
]

[tool.uv.sources]
torch = { index = "pytorch-cu118" }
torchvision = { index = "pytorch-cu118" }

[[tool.uv.index]]
name = "pytorch-cu118"
url = "https://download.pytorch.org/whl/cu118"
explicit = true

[tool.hatch.build.targets.wheel]
packages = ["gator/"]

[tool.ruff]
line-length = 80

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
